# Logistic Regression

## Importing the libraries

In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

## Importing the dataset

In [2]:
dataset = pd.read_csv('heart.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(X)

[[63.  1.  3. ...  0.  0.  1.]
 [37.  1.  2. ...  0.  0.  2.]
 [41.  0.  1. ...  2.  0.  2.]
 ...
 [68.  1.  0. ...  1.  2.  3.]
 [57.  1.  0. ...  1.  1.  3.]
 [57.  0.  1. ...  1.  1.  2.]]


## Splitting the dataset into the Training set and Test set

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 1)

In [5]:
print(X_test)

[[6.20e+01 0.00e+00 0.00e+00 1.60e+02 1.64e+02 0.00e+00 0.00e+00 1.45e+02
  0.00e+00 6.20e+00 0.00e+00 3.00e+00 3.00e+00]
 [5.60e+01 1.00e+00 1.00e+00 1.30e+02 2.21e+02 0.00e+00 0.00e+00 1.63e+02
  0.00e+00 0.00e+00 2.00e+00 0.00e+00 3.00e+00]
 [4.80e+01 1.00e+00 0.00e+00 1.30e+02 2.56e+02 1.00e+00 0.00e+00 1.50e+02
  1.00e+00 0.00e+00 2.00e+00 2.00e+00 3.00e+00]
 [6.00e+01 1.00e+00 0.00e+00 1.30e+02 2.06e+02 0.00e+00 0.00e+00 1.32e+02
  1.00e+00 2.40e+00 1.00e+00 2.00e+00 3.00e+00]
 [5.00e+01 1.00e+00 0.00e+00 1.50e+02 2.43e+02 0.00e+00 0.00e+00 1.28e+02
  0.00e+00 2.60e+00 1.00e+00 0.00e+00 3.00e+00]
 [6.30e+01 1.00e+00 0.00e+00 1.40e+02 1.87e+02 0.00e+00 0.00e+00 1.44e+02
  1.00e+00 4.00e+00 2.00e+00 2.00e+00 3.00e+00]
 [5.60e+01 1.00e+00 0.00e+00 1.30e+02 2.83e+02 1.00e+00 0.00e+00 1.03e+02
  1.00e+00 1.60e+00 0.00e+00 0.00e+00 3.00e+00]
 [4.60e+01 0.00e+00 0.00e+00 1.38e+02 2.43e+02 0.00e+00 0.00e+00 1.52e+02
  1.00e+00 0.00e+00 1.00e+00 0.00e+00 2.00e+00]
 [6.00e+01 1.00e+00 0.00

## Feature Scaling

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 0:] = sc.fit_transform(X_train[:, 0:])
X_test[:, 0:] = sc.transform(X_test[:, 0:])

In [7]:
print(X_test)

[[ 8.48629914e-01 -1.57870443e+00 -9.52961539e-01  1.65557101e+00
  -1.73764842e+00 -4.26956282e-01 -1.02481213e+00 -1.92419210e-01
  -6.95456778e-01  4.73683075e+00 -2.34749283e+00  2.26722441e+00
   1.15033515e+00]
 [ 1.93023593e-01  6.33430792e-01  3.03215035e-02 -5.55290930e-02
  -4.96498383e-01 -4.26956282e-01 -1.02481213e+00  5.73135700e-01
  -6.95456778e-01 -9.25800354e-01  9.52079135e-01 -7.13431619e-01
   1.15033515e+00]
 [-6.81118167e-01  6.33430792e-01 -9.52961539e-01 -5.55290930e-02
   2.65611287e-01  2.34216018e+00 -1.02481213e+00  2.02349315e-02
   1.43790388e+00 -9.25800354e-01  9.52079135e-01  1.27367240e+00
   1.15033515e+00]
 [ 6.30094474e-01  6.33430792e-01 -9.52961539e-01 -5.55290930e-02
  -8.23116813e-01 -4.26956282e-01 -1.02481213e+00 -7.45319978e-01
   1.43790388e+00  1.26618588e+00 -6.97706847e-01  1.27367240e+00
   1.15033515e+00]
 [-4.62582727e-01  6.33430792e-01 -9.52961539e-01  1.08520431e+00
  -1.74580189e-02 -4.26956282e-01 -1.02481213e+00 -9.15443291e-01


## Training the Logistic Regression model on the Training set

In [8]:
from sklearn.linear_model import LogisticRegression
logr = LogisticRegression()
logr.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

## Predicting a new result

In [9]:
print(logr.predict(sc.transform([[49, 1, 1, 130, 266, 0, 1, 171, 0, 0.6, 2, 0, 2]])))

[1]


## Predicting the Test set results

In [10]:
y_predictions = logr.predict(X_test)
print(np.concatenate((y_predictions.reshape(len(y_predictions), 1),
                      y_test.reshape(len(y_test), 1)), 1))

[[0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [0 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [1 0]
 [0 1]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [1 0]
 [1 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]]


## Making the Confusion Matrix

In [11]:
# accuracy of our model
from sklearn.metrics import confusion_matrix, accuracy_score
con_mat = confusion_matrix(y_test, y_predictions)
print(con_mat)
acc = accuracy_score(y_test, y_predictions)
print(acc) # 75% accuracy

[[24 11]
 [ 8 33]]
0.75
